import { Order } from "../models/order.model";
import { ORDER_STATUS } from "../models/order.model";

export async function seedOrders() {
  const exists = await Order.countDocuments();
  if (exists > 0) return;

  await Order.insertMany([
    {
      orderId: "ORD-001",
      customer: "John Doe",
      date: new Date("2024-01-05"),
      amount: 12000,
      status: ORDER_STATUS.COMPLETED,
      region: "North America",
    },
    {
      orderId: "ORD-002",
      customer: "Jane Smith",
      date: new Date("2024-01-18"),
      amount: 9000,
      status: ORDER_STATUS.PENDING,
      region: "Europe",
    },
    {
      orderId: "ORD-003",
      customer: "Alex Brown",
      date: new Date("2024-02-03"),
      amount: 18000,
      status: ORDER_STATUS.CANCELLED,
      region: "Asia",
    },
    {
      orderId: "ORD-004",
      customer: "Emma Wilson",
      date: new Date("2024-02-20"),
      amount: 14000,
      status: ORDER_STATUS.COMPLETED,
      region: "Middle East",
    },
    {
      orderId: "ORD-005",
      customer: "Liam Johnson",
      date: new Date("2024-03-04"),
      amount: 15000,
      status: ORDER_STATUS.PENDING,
      region: "North America",
    },
    {
      orderId: "ORD-006",
      customer: "Sophia Miller",
      date: new Date("2024-03-16"),
      amount: 17000,
      status: ORDER_STATUS.COMPLETED,
      region: "Europe",
    },
    {
      orderId: "ORD-007",
      customer: "Noah Davis",
      date: new Date("2024-03-29"),
      amount: 8000,
      status: ORDER_STATUS.CANCELLED,
      region: "Asia",
    },
    {
      orderId: "ORD-008",
      customer: "Olivia Garcia",
      date: new Date("2024-04-06"),
      amount: 22000,
      status: ORDER_STATUS.COMPLETED,
      region: "Middle East",
    },
    {
      orderId: "ORD-009",
      customer: "William Martinez",
      date: new Date("2024-04-14"),
      amount: 19000,
      status: ORDER_STATUS.PENDING,
      region: "North America",
    },
    {
      orderId: "ORD-010",
      customer: "Ava Rodriguez",
      date: new Date("2024-04-28"),
      amount: 13000,
      status: ORDER_STATUS.COMPLETED,
      region: "Europe",
    },
    {
      orderId: "ORD-011",
      customer: "James Anderson",
      date: new Date("2024-05-02"),
      amount: 24000,
      status: ORDER_STATUS.COMPLETED,
      region: "Asia",
    },
    {
      orderId: "ORD-012",
      customer: "Isabella Thomas",
      date: new Date("2024-05-11"),
      amount: 21000,
      status: ORDER_STATUS.PENDING,
      region: "Middle East",
    },
    {
      orderId: "ORD-013",
      customer: "Benjamin Taylor",
      date: new Date("2024-05-21"),
      amount: 16000,
      status: ORDER_STATUS.CANCELLED,
      region: "North America",
    },
    {
      orderId: "ORD-014",
      customer: "Mia Moore",
      date: new Date("2024-06-01"),
      amount: 33000,
      status: ORDER_STATUS.COMPLETED,
      region: "Europe",
    },
    {
      orderId: "ORD-015",
      customer: "Lucas Jackson",
      date: new Date("2024-06-09"),
      amount: 29000,
      status: ORDER_STATUS.COMPLETED,
      region: "Asia",
    },
    {
      orderId: "ORD-016",
      customer: "Charlotte Martin",
      date: new Date("2024-06-18"),
      amount: 26000,
      status: ORDER_STATUS.PENDING,
      region: "Middle East",
    },
    {
      orderId: "ORD-017",
      customer: "Henry Lee",
      date: new Date("2024-07-03"),
      amount: 18000,
      status: ORDER_STATUS.COMPLETED,
      region: "North America",
    },
    {
      orderId: "ORD-018",
      customer: "Amelia Perez",
      date: new Date("2024-07-14"),
      amount: 20000,
      status: ORDER_STATUS.CANCELLED,
      region: "Europe",
    },
    {
      orderId: "ORD-019",
      customer: "Daniel White",
      date: new Date("2024-07-22"),
      amount: 15000,
      status: ORDER_STATUS.PENDING,
      region: "Asia",
    },
    {
      orderId: "ORD-020",
      customer: "Harper Harris",
      date: new Date("2024-07-30"),
      amount: 17000,
      status: ORDER_STATUS.COMPLETED,
      region: "Middle East",
    },
  ]);

  console.log("✅ 20 Orders seeded with 4 clean regions");
}
